### ISSUE TITLE
use reticulate

### ISSUE THREAD

**Issue by stillmatic** [stillmatic/quiltr#6]
if we need to delegate stuff to python, it's probably better to do it via [reticulate](https://github.com/rstudio/reticulate) or similar package, than to do it via my hacky shell calls.

**Comment by tnederlof** [comment]
Very interesting package and since it's from that team I'm sure it works well. I'm happy to have a go at it and submit a PR.

**Comment by stillmatic** [comment]
https://github.com/stillmatic/quiltr/commit/9a42840fd10e1d5d38a63b6ae85cf0af2a36cad4 begins usage of `reticulate`. there's a certain minimalism of solely relying on shell commands but i'm happy to move away from them.

**Comment by stillmatic** [comment]
https://github.com/stillmatic/quiltr/commit/636dfee790ab1ca4e30c37a71dae8ebd502386fe
